// Web Worker: owns the WASM module instance and forwards control messages
// to it. The 100 Hz simulation tick runs inside the C++ engine itself
// (Simulation::run_loop(), a std::thread spawned by startSimulation() and
// compiled to a real OS thread via Emscripten pthreads) — this worker does
// not run its own timing loop. The main thread reads StateFrames directly
// out of the shared ring buffer at 60 fps via bridge/ring_reader.ts; this
// worker's only job after init is to relay UI control messages into WASM
// ccall()s.

import type { FaultConfig, MCStats, OrbitForgeModule, ScenarioConfig } from './bridge/wasm_types.js'

export interface InitMessage {
  type: 'init'
  payload: ScenarioConfig
}
export interface ControlMessage {
  type: 'start' | 'pause' | 'reset'
}
export interface SetFaultMessage {
  type: 'set_fault'
  payload: FaultConfig
}
// Only safe to send while paused/idle — Simulation::set_sim_speed() (C++)
// is unsynchronized against run_loop()'s own thread, by design (see its
// doc comment): nothing else mutates cfg_ while that thread could be
// running, so this preserves the same invariant rather than needing a new
// one. RunControls only ever sends this right before resuming from pause.
export interface SetSimSpeedMessage {
  type: 'set_sim_speed'
  payload: { simSpeed: number }
}
export interface RunMonteCarloMessage {
  type: 'run_monte_carlo'
  payload: { nRuns: number; seed: number }
}
export type WorkerRequest =
  | InitMessage
  | ControlMessage
  | SetFaultMessage
  | SetSimSpeedMessage
  | RunMonteCarloMessage

export interface RingBufferReadyMessage {
  type: 'ring_buffer_ready'
  payload: {
    sharedArrayBuffer: SharedArrayBuffer
    ringBufferPtr: number
    ringBufferCapacity: number
  }
}
export interface McResultsMessage {
  type: 'mc_results'
  payload: MCStats
}
export type WorkerResponse = RingBufferReadyMessage | McResultsMessage

type WasmModuleFactory = (overrides?: { locateFile?: (path: string) => string }) => Promise<OrbitForgeModule>

let wasmModulePromise: Promise<OrbitForgeModule> | undefined

async function loadWasmModule(): Promise<OrbitForgeModule> {
  // orbitforge.js is generated by scripts/build_wasm.sh into web/public/ at
  // build time (gitignored artifact, not present in source control), so
  // TypeScript can't resolve it statically. Vite's dev server additionally
  // refuses to serve a public/ file through a plain `import('/orbitforge.js')`
  // (its module graph treats public/ as "reference by URL only"). Fetching
  // the source as text and importing it from a blob: URL sidesteps that
  // restriction in both dev and the built bundle. Because the blob URL has
  // no real path, locateFile is overridden so the module's internal fetches
  // for orbitforge.wasm and the pthread worker script resolve back to the
  // site root where build_wasm.sh actually places them.
  const code = await (await fetch('/orbitforge.js')).text()
  const blobUrl = URL.createObjectURL(new Blob([code], { type: 'text/javascript' }))
  try {
    const imported = (await import(/* @vite-ignore */ blobUrl)) as { default: WasmModuleFactory }
    return imported.default({ locateFile: (path: string) => `/${path}` })
  } finally {
    URL.revokeObjectURL(blobUrl)
  }
}

function getWasmModule(): Promise<OrbitForgeModule> {
  if (!wasmModulePromise) wasmModulePromise = loadWasmModule()
  return wasmModulePromise
}

function initScenario(module: OrbitForgeModule, cfg: ScenarioConfig): void {
  module.ccall(
    'init_scenario',
    null,
    ['string', 'string', 'number', 'number', 'number', 'number', 'number',
     'number', 'number', 'number', 'number', 'number', 'number',
     // Phase 5: 6DOF (CLAUDE.md §21) — appended after the Phase 1-4 params,
     // matching wasm_api.cpp's extern "C" init_scenario signature exactly.
     'number', 'number', 'number', 'number', 'number', 'number', 'number',
     'number', 'number', 'number'],
    [cfg.tleLine1, cfg.tleLine2, cfg.gpsSigma, cfg.imuSigma,
     cfg.enableJ2 ? 1 : 0, cfg.enableDrag ? 1 : 0, cfg.enableSrp ? 1 : 0,
     cfg.dragCoeff, cfg.areaToMass, cfg.qPos, cfg.qVel, cfg.simSpeed, cfg.seed,
     cfg.inertiaX, cfg.inertiaY, cfg.inertiaZ, cfg.gyroSigma, cfg.magSigma,
     cfg.qAtt, cfg.qOmega, cfg.initOmegaX, cfg.initOmegaY, cfg.initOmegaZ],
  )

  const ringBufferPtr = module.ccall('get_ring_buffer_ptr', 'number', [], []) as number
  const ringBufferCapacity = module.ccall('get_ring_buffer_capacity', 'number', [], []) as number

  // The WASM heap is a SharedArrayBuffer because the module is built with
  // pthreads (-sUSE_PTHREADS=1) — required for cross-thread memory access
  // without postMessage copies.
  const response: RingBufferReadyMessage = {
    type: 'ring_buffer_ready',
    payload: {
      sharedArrayBuffer: module.HEAPF64.buffer as SharedArrayBuffer,
      ringBufferPtr,
      ringBufferCapacity,
    },
  }
  self.postMessage(response)
}

// Reads `len` consecutive doubles starting at the byte offset `ptr` returned
// by one of the get_mc_*_ptr() exports. Same byte-offset/8 = float64-index
// convention as bridge/ring_reader.ts, since both read out of the same WASM
// linear memory.
function readF64Array(module: OrbitForgeModule, ptr: number, len: number): number[] {
  const base = ptr / 8
  const out = new Array<number>(len)
  for (let i = 0; i < len; i++) out[i] = module.HEAPF64[base + i]!
  return out
}

// run_monte_carlo blocks this worker (not the main thread) for the whole
// campaign — see wasm_api.cpp's comment on the export. The result arrays
// are copied out of WASM memory immediately after the call returns, before
// any other ccall can run_monte_carlo() again and reallocate them
// underneath a stale pointer.
function runMonteCarlo(module: OrbitForgeModule, nRuns: number, seed: number): MCStats {
  module.ccall('run_monte_carlo', null, ['number', 'number'], [nRuns, seed])

  const nSteps = module.ccall('get_mc_n_steps', 'number', [], []) as number
  const nRunsActual = module.ccall('get_mc_n_runs', 'number', [], []) as number
  const rmsPosPtr = module.ccall('get_mc_rms_pos_ptr', 'number', [], []) as number
  const rmsVelPtr = module.ccall('get_mc_rms_vel_ptr', 'number', [], []) as number
  const neesPtr = module.ccall('get_mc_nees_ptr', 'number', [], []) as number
  const nisPtr = module.ccall('get_mc_nis_ptr', 'number', [], []) as number
  const finalPosErrPtr = module.ccall('get_mc_final_pos_err_ptr', 'number', [], []) as number

  return {
    rmsPosPerStep: readF64Array(module, rmsPosPtr, nSteps),
    rmsVelPerStep: readF64Array(module, rmsVelPtr, nSteps),
    neesPerStep: readF64Array(module, neesPtr, nSteps),
    nisPerStep: readF64Array(module, nisPtr, nSteps),
    finalPosErrPerRun: readF64Array(module, finalPosErrPtr, nRunsActual),
    neesLower: module.ccall('get_mc_nees_lower', 'number', [], []) as number,
    neesUpper: module.ccall('get_mc_nees_upper', 'number', [], []) as number,
    nisLower: module.ccall('get_mc_nis_lower', 'number', [], []) as number,
    nisUpper: module.ccall('get_mc_nis_upper', 'number', [], []) as number,
  }
}

self.addEventListener('message', (e: MessageEvent<WorkerRequest>) => {
  const msg = e.data
  void getWasmModule().then((module) => {
    switch (msg.type) {
      case 'init':
        initScenario(module, msg.payload)
        break
      case 'start':
        module.ccall('start_simulation', null, [], [])
        break
      case 'pause':
        module.ccall('pause_simulation', null, [], [])
        break
      case 'reset':
        module.ccall('reset_simulation', null, [], [])
        break
      case 'set_fault':
        module.ccall(
          'set_fault',
          null,
          ['number', 'number', 'number', 'number'],
          [msg.payload.type, msg.payload.onsetT, msg.payload.duration, msg.payload.magnitude],
        )
        break
      case 'set_sim_speed':
        module.ccall('set_sim_speed', null, ['number'], [msg.payload.simSpeed])
        break
      case 'run_monte_carlo': {
        const stats = runMonteCarlo(module, msg.payload.nRuns, msg.payload.seed)
        const response: McResultsMessage = { type: 'mc_results', payload: stats }
        self.postMessage(response)
        break
      }
    }
  })
})
