// Web Worker: owns the WASM module instance and forwards control messages
// to it. The 100 Hz simulation tick runs inside the C++ engine itself
// (Simulation::run_loop(), a std::thread spawned by startSimulation() and
// compiled to a real OS thread via Emscripten pthreads) — this worker does
// not run its own timing loop. The main thread reads StateFrames directly
// out of the shared ring buffer at 60 fps via bridge/ring_reader.ts; this
// worker's only job after init is to relay UI control messages into WASM
// ccall()s. See CLAUDE.md §4.

import type { FaultConfig, OrbitForgeModule, ScenarioConfig } from './bridge/wasm_types.js'

export interface InitMessage {
  type: 'init'
  payload: ScenarioConfig
}
export interface ControlMessage {
  type: 'start' | 'pause' | 'reset'
}
export interface SetFaultMessage {
  type: 'set_fault'
  payload: FaultConfig
}
export type WorkerRequest = InitMessage | ControlMessage | SetFaultMessage

export interface RingBufferReadyMessage {
  type: 'ring_buffer_ready'
  payload: {
    sharedArrayBuffer: SharedArrayBuffer
    ringBufferPtr: number
    ringBufferCapacity: number
  }
}
export type WorkerResponse = RingBufferReadyMessage

type WasmModuleFactory = () => Promise<OrbitForgeModule>

let wasmModulePromise: Promise<OrbitForgeModule> | undefined

async function loadWasmModule(): Promise<OrbitForgeModule> {
  // orbitforge.js is generated by scripts/build_wasm.sh into web/public/ at
  // build time (gitignored artifact, not present in source control). The
  // dynamic import is intentionally untyped: TypeScript can't resolve a
  // module that doesn't exist in this source tree, and using a runtime
  // (non-literal) specifier keeps it from trying to.
  const modulePath = '/orbitforge.js'
  const imported = (await import(/* @vite-ignore */ modulePath)) as { default: WasmModuleFactory }
  return imported.default()
}

function getWasmModule(): Promise<OrbitForgeModule> {
  if (!wasmModulePromise) wasmModulePromise = loadWasmModule()
  return wasmModulePromise
}

function initScenario(module: OrbitForgeModule, cfg: ScenarioConfig): void {
  module.ccall(
    'init_scenario',
    null,
    ['string', 'string', 'number', 'number', 'number', 'number', 'number',
     'number', 'number', 'number', 'number', 'number', 'number'],
    [cfg.tleLine1, cfg.tleLine2, cfg.gpsSigma, cfg.imuSigma,
     cfg.enableJ2 ? 1 : 0, cfg.enableDrag ? 1 : 0, cfg.enableSrp ? 1 : 0,
     cfg.dragCoeff, cfg.areaToMass, cfg.qPos, cfg.qVel, cfg.simSpeed, cfg.seed],
  )

  const ringBufferPtr = module.ccall('get_ring_buffer_ptr', 'number', [], []) as number
  const ringBufferCapacity = module.ccall('get_ring_buffer_capacity', 'number', [], []) as number

  // The WASM heap is a SharedArrayBuffer because the module is built with
  // pthreads (-sUSE_PTHREADS=1) — required for cross-thread memory access
  // without postMessage copies.
  const response: RingBufferReadyMessage = {
    type: 'ring_buffer_ready',
    payload: {
      sharedArrayBuffer: module.HEAPF64.buffer as SharedArrayBuffer,
      ringBufferPtr,
      ringBufferCapacity,
    },
  }
  self.postMessage(response)
}

self.addEventListener('message', (e: MessageEvent<WorkerRequest>) => {
  const msg = e.data
  void getWasmModule().then((module) => {
    switch (msg.type) {
      case 'init':
        initScenario(module, msg.payload)
        break
      case 'start':
        module.ccall('start_simulation', null, [], [])
        break
      case 'pause':
        module.ccall('pause_simulation', null, [], [])
        break
      case 'reset':
        module.ccall('reset_simulation', null, [], [])
        break
      case 'set_fault':
        module.ccall(
          'set_fault',
          null,
          ['number', 'number', 'number', 'number'],
          [msg.payload.type, msg.payload.onsetT, msg.payload.duration, msg.payload.magnitude],
        )
        break
    }
  })
})
